version: '2'
services:
  node_react:
    image: node:8
    container_name: node_react
    build: ./
    # image: 'node_react:latest'
    # working_dir: /usr/src/app
    working_dir: /usr/src/app/ftreact
    volumes:
      - ./app:/usr/src/app
    expose:
      - '3001'
    ports:
      - '3001:3001'
    # This is a dependency free script to make this container keep running
    # command: 'node app.js'
    command: 'npm start'

networks:
  default:
    external:
      name: docker_node_default
